# The URL the site will be built for
base_url = "https://teuze.github.io"
theme = "terminus"
title = "Teuze"

compile_sass = true

build_search_index = true

taxonomies = [{ name = "tags", feed = true }]

[markdown]

render_emoji = true
highlight_code = true
highlight_theme = "visual-studio-dark"

insert_anchor_links = "right"

[extra]

favicon_emoji = ":w"

color_scheme = "gruvbox-dark"

copyright = "Made with :heart: using [Zola](https://www.getzola.org) and [terminus](https://eyalkalderon.com/terminus)"

main_menu = [
    { name = "blog", url = "/", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]

socials = [
    { name = "email", url = "mailto:richard.jarry@protonmail.com" },
    { name = "github", url = "https://github.com/Teuze" },
    { name = "linkedin", url = "https://www.linkedin.com/in/richard-jarry-01/" },
]

[extra.content_security_policy]
enable = false
